# WhatATheme
markdown: kramdown

# URL of the Site
url: ''
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 

# Title of the Site
title: lee's archive home
# Description of the Site
description: 지나온 시간들을 저장합니다.
# URL of Image of the Site
site-image: /WhatATheme/assets/images/SamplePost.png
# Keywords of the Site
site-keywords: Site, Template, Theme
# URL for the Image of custom Favicon
favicon-url: 

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: https://images.pexels.com/photos/220444/pexels-photo-220444.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: tkddn4508@naver.com
facebook_username: profile.php?id=100004227668934
#twitter_username: /
instagram_username: leesnagwoo
linkedin_username: 상우-이-69a2b7205
github_username:  gomtings
youtube_channel_id: UCx9_CTrR6V2gG69TFouNBrg
#reddit_username: /
#behance_username: /
#dribbble_username: /
#spotify_username: /

# Google Analytics
google-analytics: UA-163806439-1

# Disqus
disqus-shortname: 이상우(Lee Sang Woo)

# Name of the Author
author-name: 이상우(Lee Sang Woo)
# URL for the Image of the Author
author-image: /assets/images/profile-picture.jpg
# 60 Words About the Author
author-about: 전공 :한림대학교 소프트웨어융합대학 빅데이터(복수전공:스마트IOT)
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://github.com/gomtings

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
